name: Branch Protection and Notification

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  protect_and_notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Contributors
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.WACKDONALDS_TOKEN}}
        script: |
          const issueNumber = context.issue.number;
          const contributors = await github.repos.listContributors({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          contributors.data.forEach(async (contributor) => {
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `@${contributor.login} A new pull request has been created.`,
            });
          });
